apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "xkcd.fullname" . }}
  namespace: {{ .Values.ingressNamespace | default .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  {{ if .Values.ingressClassName -}}
  ingressClassName: {{ .Values.ingressClassName | quote }}
  {{- end }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port:
              number: 8080
